---

plugins:
  - functional

extends:
  - airbnb
  - "plugin:jest/recommended"
  - "plugin:functional/external-recommended"
  - "plugin:functional/recommended"

parser: babel-eslint

env:
  browser: true
  node: true
  jest: true

settings:
  import/resolver:
    - node
    - webpack

rules:
  import/extensions: 0
  react/prop-types: 0
  no-console: 0
  functional/no-conditional-statement: 0
  functional/no-expression-statement: 0
  functional/immutable-data: 0
  functional/functional-parameters: 0
  functional/no-try-statement: 0
  functional/no-throw-statement: 0
  react/jsx-props-no-spreading: 0
  react/button-has-type: 0
  react/destructuring-assignment: 0
  padded-blocks: 0
  no-param-reassign: 0
  import/prefer-default-export: 0
  arrow-body-style: 0
